project_id = "amssskednvpjftefeyys"
[functions.openai-questions]
enabled = true
verify_jwt = true
import_map = "./functions/openai-questions/import_map.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/openai-questions/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/openai-questions/*.html" ]

[functions.openai-recommendations]
enabled = true
verify_jwt = true
import_map = "./functions/openai-recommendations/import_map.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/openai-recommendations/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/openai-recommendations/*.html" ]

[functions.tmdb-proxy]
enabled = true
verify_jwt = true
import_map = "./functions/tmdb-proxy/import_map.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/tmdb-proxy/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/tmdb-proxy/*.html" ]

[functions.google-books-proxy]
enabled = true
verify_jwt = true
import_map = "./functions/google-books-proxy/import_map.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/google-books-proxy/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/google-books-proxy/*.html" ]
