// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amssskednvpjftefeyys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtc3Nza2VkbnZwamZ0ZWZleXlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MDgxMjMsImV4cCI6MjA2NTE4NDEyM30.ss7Vze6XeYXULkfb7bOAI3EewvZc_HqOyLAuoOK5deA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);